### ISSUE TITLE
Is backup.sh to generic a name?

### ISSUE THREAD

**Issue by niftyhacking** [AlexWinder/letsencrypt-backup#1]
Is the name of this script too generic?

One suggestion is  " le-backup.sh "

Simple enough to do but there are dozens of activities where backups are needed.
They all cannot be called backup.sh   ;-)

**Comment by AlexWinder** [comment]
The `backup.sh` is an example script anyway, you are free to rename it however you want. 

The script itself by its very nature is due to be edited anyway as your requirements may not be the same as I have put in the script (number of days of backups, backup location, LE source, etc.). Perhaps at some point I (or someone with a PR) could change the script so that you can have a separate configuration file, or use environment variables, to be used in the script rather than hard-coding them.

**Comment by AlexWinder** [comment]
Hey @niftyhacking 

Just an update to let you know that I've recently updated the script based on your recommendations to make it more descriptive. The script now also has support for named arguments to avoid users needing to manually configure the script and to make it more user-friendly.
